name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # one scheduled build on the first day of every month at 3:05
    - cron: '5 3 1 * *'

jobs:
  ubuntu:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        compiler: [gcc, clang]
    runs-on: ${{ matrix.os }}
    env:
      CC: "${{ matrix.compiler == 'gcc' && 'gcc' || 'clang' }}"
      CFLAGS: "${{ matrix.compiler == 'gcc' && '-Wall -Wextra' || '-Weverything -Wno-padded' }}"
    steps:
      - uses: actions/checkout@v2

      # libgd3 removal needed due to https://github.com/actions/virtual-environments/issues/2139
      - name: dependencies
        run: |
          sudo apt-get update
          sudo apt-get remove libgd3
          sudo apt-get -y install libsqlite3-dev libgd-dev check

      - name: configure gcc
        if: ${{ matrix.compiler == 'gcc' }}
        run: |
          gcc --version
          ./configure --enable-werror

      - name: configure clang
        if: ${{ matrix.compiler == 'clang' }}
        run: |
          clang --version
          ./configure

      - name: make check
        run: make check

      - name: version
        run: ./vnstat --version

  ubuntu_clang_sanitizers:
    runs-on: ubuntu-20.04
    env:
      CC: clang
      CFLAGS: '-Wall -Wextra -O1 -g -fsanitize=address -fsanitize-address-use-after-scope -fno-omit-frame-pointer -fsanitize=undefined -fsanitize=nullability -fsanitize=implicit-conversion -fsanitize=integer -fsanitize=float-divide-by-zero -fsanitize=local-bounds'
      ASAN_OPTIONS: strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1
      UBSAN_OPTIONS: print_stacktrace=1:print_summary=1:halt_on_error=1
    steps:
      - uses: actions/checkout@v2

      # libgd3 removal needed due to https://github.com/actions/virtual-environments/issues/2139
      - name: dependencies
        run: |
          sudo apt-get update
          sudo apt-get remove libgd3
          sudo apt-get -y install libsqlite3-dev libgd-dev check

      - name: configure
        run: |
          clang --version
          ./configure --enable-werror

      - name: make check
        run: make check

      - name: version
        run: ./vnstat --version

      - name: verify log
        run: grep -iP 'sanitizer|runtime error' check_vnstat.log && exit 1 || true

  ubuntu_clang_analyzer:
    runs-on: ubuntu-20.04
    env:
      CC: clang
      CFLAGS: '-Wall -Wextra'
    steps:
      - uses: actions/checkout@v2

      # libgd3 removal needed due to https://github.com/actions/virtual-environments/issues/2139
      - name: dependencies
        run: |
          sudo apt-get update
          sudo apt-get remove libgd3
          sudo apt-get -y install libsqlite3-dev libgd-dev check clang-tools

      - name: configure
        run: |
          clang --version
          scan-build -analyze-headers --status-bugs ./configure --enable-werror

      - name: make
        run: scan-build -analyze-headers --status-bugs make

  macos_clang:
    runs-on: macos-10.15
    env:
      CC: clang
      CFLAGS: '-Weverything -Wno-padded -Wno-poison-system-directories'
    steps:
      - uses: actions/checkout@v2

      - name: dependencies
        run: brew install sqlite gd check

      - name: configure
        run: |
          clang --version
          ./configure

      - name: make check
        run: make check

      - name: version
        run: ./vnstat --version
